### ISSUE TITLE
Add Ride Pilot

### ISSUE THREAD

**Issue by barbeau** [luqmaan/awesome-transit#97]
Originally by RideConnection:
https://github.com/rideconnection/ridepilot

Looks like Cambridge Systematics now has an updated version:
https://github.com/camsys/ridepilot

CS marketing site:
http://camsys.software/products/ridepilot

Same as other projects that have a main and fork on Github - if the above project READMEs are updated to reflect the current status of the projects (is Ride Connection version deprecated?) then we can add to the list.

**Comment by barbeau** [comment]
@keviniano and @sheldonabrown / @xudongcamsys I'd like to add Ride Pilot to this list (awesome-transit), but currently it's not clear how the Ride Connection (https://github.com/rideconnection/ridepilot) and Cambridge Systematics (https://github.com/camsys/ridepilot) projects are different.  For example, is the Ride Connection version deprecated?

Would you be able to update the READMEs to make the relationship between the two projects clearer?

**Comment by xudongcamsys** [comment]
My understanding is the Ride Connection version is still running on its own, but there hasn't been any new feature implemented in the past 2-3 years. The CS version is forked off Ride Connection version and has been under active development since then. CS has been working with Utah Transit Authority to expand Ride Pilot capabilities to meet their needs.

**Comment by keviniano** [comment]
The Ride Connection version is deprecated. The CS fork is the only active one I know of.

I’ll take a look at updating the Ride Connection version to point to the CS version.

**Comment by keviniano** [comment]
I just updated the Ride Connection version to say that it’s not maintained. I included a link to the CS version.

**Comment by barbeau** [comment]
Thanks @keviniano!  I just added it to the list.
